// Copyright 2025 itlab-vision
// automatically generated by the FlatBuffers compiler, do not modify

#ifndef MODULES_FB_GENERATED_ATTRACTIONS_GENERATED_HPP_
#define MODULES_FB_GENERATED_ATTRACTIONS_GENERATED_HPP_

#include <vector>

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
                  FLATBUFFERS_VERSION_MINOR == 2 &&
                  FLATBUFFERS_VERSION_REVISION == 10,
              "Non-compatible flatbuffers version included");

namespace AttractionsData {

struct Coordinates;

struct ExtraField;
struct ExtraFieldBuilder;

struct AttractionInfo;
struct AttractionInfoBuilder;

struct Attraction;
struct AttractionBuilder;

struct Attractions;
struct AttractionsBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Coordinates FLATBUFFERS_FINAL_CLASS {
 private:
    double latitude_;
    double longitude_;

 public:
    Coordinates() : latitude_(0), longitude_(0) {}
    Coordinates(double _latitude, double _longitude)
        : latitude_(::flatbuffers::EndianScalar(_latitude)),
          longitude_(::flatbuffers::EndianScalar(_longitude)) {}
    double latitude() const { return ::flatbuffers::EndianScalar(latitude_); }
    double longitude() const { return ::flatbuffers::EndianScalar(longitude_); }
};
FLATBUFFERS_STRUCT_END(Coordinates, 16);

struct ExtraField FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef ExtraFieldBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_KEY = 4,
        VT_VALUE = 6
    };
    const ::flatbuffers::String* key() const {
        return GetPointer<const ::flatbuffers::String*>(VT_KEY);
    }
    bool KeyCompareLessThan(const ExtraField* const o) const {
        return *key() < *o->key();
    }
    int KeyCompareWithValue(const char* _key) const {
        return strcmp(key()->c_str(), _key);
    }
    template <typename StringType>
    int KeyCompareWithValue(const StringType& _key) const {
        if (key()->c_str() < _key) return -1;
        if (_key < key()->c_str()) return 1;
        return 0;
    }
    const ::flatbuffers::String* value() const {
        return GetPointer<const ::flatbuffers::String*>(VT_VALUE);
    }
    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) &&
               VerifyOffsetRequired(verifier, VT_KEY) &&
               verifier.VerifyString(key()) &&
               VerifyOffset(verifier, VT_VALUE) &&
               verifier.VerifyString(value()) && verifier.EndTable();
    }
};

struct ExtraFieldBuilder {
    typedef ExtraField Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_key(::flatbuffers::Offset<::flatbuffers::String> key) {
        fbb_.AddOffset(ExtraField::VT_KEY, key);
    }
    void add_value(::flatbuffers::Offset<::flatbuffers::String> value) {
        fbb_.AddOffset(ExtraField::VT_VALUE, value);
    }
    explicit ExtraFieldBuilder(::flatbuffers::FlatBufferBuilder& _fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<ExtraField> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<ExtraField>(end);
        fbb_.Required(o, ExtraField::VT_KEY);
        return o;
    }
};

inline ::flatbuffers::Offset<ExtraField> CreateExtraField(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    ::flatbuffers::Offset<::flatbuffers::String> key = 0,
    ::flatbuffers::Offset<::flatbuffers::String> value = 0) {
    ExtraFieldBuilder builder_(_fbb);
    builder_.add_value(value);
    builder_.add_key(key);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<ExtraField> CreateExtraFieldDirect(
    ::flatbuffers::FlatBufferBuilder& _fbb, const char* key = nullptr,
    const char* value = nullptr) {
    auto key__ = key ? _fbb.CreateString(key) : 0;
    auto value__ = value ? _fbb.CreateString(value) : 0;
    return AttractionsData::CreateExtraField(_fbb, key__, value__);
}

struct AttractionInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef AttractionInfoBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_TYPE = 4,
        VT_NAME = 6,
        VT_EXTRA_FIELDS = 8
    };
    const ::flatbuffers::String* type() const {
        return GetPointer<const ::flatbuffers::String*>(VT_TYPE);
    }
    const ::flatbuffers::String* name() const {
        return GetPointer<const ::flatbuffers::String*>(VT_NAME);
    }
    const ::flatbuffers::Vector<
        ::flatbuffers::Offset<AttractionsData::ExtraField>>*
    extra_fields() const {
        return GetPointer<const ::flatbuffers::Vector<
            ::flatbuffers::Offset<AttractionsData::ExtraField>>*>(
            VT_EXTRA_FIELDS);
    }
    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) && VerifyOffset(verifier, VT_TYPE) &&
               verifier.VerifyString(type()) &&
               VerifyOffset(verifier, VT_NAME) &&
               verifier.VerifyString(name()) &&
               VerifyOffset(verifier, VT_EXTRA_FIELDS) &&
               verifier.VerifyVector(extra_fields()) &&
               verifier.VerifyVectorOfTables(extra_fields()) &&
               verifier.EndTable();
    }
};

struct AttractionInfoBuilder {
    typedef AttractionInfo Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_type(::flatbuffers::Offset<::flatbuffers::String> type) {
        fbb_.AddOffset(AttractionInfo::VT_TYPE, type);
    }
    void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
        fbb_.AddOffset(AttractionInfo::VT_NAME, name);
    }
    void add_extra_fields(
        ::flatbuffers::Offset<::flatbuffers::Vector<
            ::flatbuffers::Offset<AttractionsData::ExtraField>>>
            extra_fields) {
        fbb_.AddOffset(AttractionInfo::VT_EXTRA_FIELDS, extra_fields);
    }
    explicit AttractionInfoBuilder(::flatbuffers::FlatBufferBuilder& _fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<AttractionInfo> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<AttractionInfo>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<AttractionInfo> CreateAttractionInfo(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    ::flatbuffers::Offset<::flatbuffers::String> type = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<
        ::flatbuffers::Offset<AttractionsData::ExtraField>>>
        extra_fields = 0) {
    AttractionInfoBuilder builder_(_fbb);
    builder_.add_extra_fields(extra_fields);
    builder_.add_name(name);
    builder_.add_type(type);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<AttractionInfo> CreateAttractionInfoDirect(
    ::flatbuffers::FlatBufferBuilder& _fbb, const char* type = nullptr,
    const char* name = nullptr,
    std::vector<::flatbuffers::Offset<AttractionsData::ExtraField>>*
        extra_fields = nullptr) {
    auto type__ = type ? _fbb.CreateString(type) : 0;
    auto name__ = name ? _fbb.CreateString(name) : 0;
    auto extra_fields__ =
        extra_fields
            ? _fbb.CreateVectorOfSortedTables<AttractionsData::ExtraField>(
                  extra_fields)
            : 0;
    return AttractionsData::CreateAttractionInfo(_fbb, type__, name__,
                                                 extra_fields__);
}

struct Attraction FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef AttractionBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_INFO = 4,
        VT_COORDS = 6
    };
    const AttractionsData::AttractionInfo* info() const {
        return GetPointer<const AttractionsData::AttractionInfo*>(VT_INFO);
    }
    const AttractionsData::Coordinates* coords() const {
        return GetStruct<const AttractionsData::Coordinates*>(VT_COORDS);
    }
    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) && VerifyOffset(verifier, VT_INFO) &&
               verifier.VerifyTable(info()) &&
               VerifyField<AttractionsData::Coordinates>(verifier, VT_COORDS,
                                                         8) &&
               verifier.EndTable();
    }
};

struct AttractionBuilder {
    typedef Attraction Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_info(::flatbuffers::Offset<AttractionsData::AttractionInfo> info) {
        fbb_.AddOffset(Attraction::VT_INFO, info);
    }
    void add_coords(const AttractionsData::Coordinates* coords) {
        fbb_.AddStruct(Attraction::VT_COORDS, coords);
    }
    explicit AttractionBuilder(::flatbuffers::FlatBufferBuilder& _fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<Attraction> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<Attraction>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<Attraction> CreateAttraction(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    ::flatbuffers::Offset<AttractionsData::AttractionInfo> info = 0,
    const AttractionsData::Coordinates* coords = nullptr) {
    AttractionBuilder builder_(_fbb);
    builder_.add_coords(coords);
    builder_.add_info(info);
    return builder_.Finish();
}

struct Attractions FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef AttractionsBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_DATA = 4
    };
    const ::flatbuffers::Vector<
        ::flatbuffers::Offset<AttractionsData::Attraction>>*
    data() const {
        return GetPointer<const ::flatbuffers::Vector<
            ::flatbuffers::Offset<AttractionsData::Attraction>>*>(VT_DATA);
    }
    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) && VerifyOffset(verifier, VT_DATA) &&
               verifier.VerifyVector(data()) &&
               verifier.VerifyVectorOfTables(data()) && verifier.EndTable();
    }
};

struct AttractionsBuilder {
    typedef Attractions Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_data(::flatbuffers::Offset<::flatbuffers::Vector<
                      ::flatbuffers::Offset<AttractionsData::Attraction>>>
                      data) {
        fbb_.AddOffset(Attractions::VT_DATA, data);
    }
    explicit AttractionsBuilder(::flatbuffers::FlatBufferBuilder& _fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<Attractions> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<Attractions>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<Attractions> CreateAttractions(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<
        ::flatbuffers::Offset<AttractionsData::Attraction>>>
        data = 0) {
    AttractionsBuilder builder_(_fbb);
    builder_.add_data(data);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<Attractions> CreateAttractionsDirect(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    const std::vector<::flatbuffers::Offset<AttractionsData::Attraction>>*
        data = nullptr) {
    auto data__ =
        data ? _fbb.CreateVector<
                   ::flatbuffers::Offset<AttractionsData::Attraction>>(*data)
             : 0;
    return AttractionsData::CreateAttractions(_fbb, data__);
}

inline const AttractionsData::Attractions* GetAttractions(const void* buf) {
    return ::flatbuffers::GetRoot<AttractionsData::Attractions>(buf);
}

inline const AttractionsData::Attractions* GetSizePrefixedAttractions(
    const void* buf) {
    return ::flatbuffers::GetSizePrefixedRoot<AttractionsData::Attractions>(
        buf);
}

inline bool VerifyAttractionsBuffer(::flatbuffers::Verifier& verifier) {
    return verifier.VerifyBuffer<AttractionsData::Attractions>(nullptr);
}

inline bool VerifySizePrefixedAttractionsBuffer(
    ::flatbuffers::Verifier& verifier) {
    return verifier.VerifySizePrefixedBuffer<AttractionsData::Attractions>(
        nullptr);
}

inline void FinishAttractionsBuffer(
    ::flatbuffers::FlatBufferBuilder& fbb,
    ::flatbuffers::Offset<AttractionsData::Attractions> root) {
    fbb.Finish(root);
}

inline void FinishSizePrefixedAttractionsBuffer(
    ::flatbuffers::FlatBufferBuilder& fbb,
    ::flatbuffers::Offset<AttractionsData::Attractions> root) {
    fbb.FinishSizePrefixed(root);
}

}  // namespace AttractionsData

#endif  // MODULES_FB_GENERATED_ATTRACTIONS_GENERATED_HPP_
