// Copyright 2025 itlab-vision
// automatically generated by the FlatBuffers compiler, do not modify

#ifndef MODULES_FB_GENERATED_DISTRICTS_GENERATED_HPP_
#define MODULES_FB_GENERATED_DISTRICTS_GENERATED_HPP_

#include <vector>

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
                  FLATBUFFERS_VERSION_MINOR == 2 &&
                  FLATBUFFERS_VERSION_REVISION == 10,
              "Non-compatible flatbuffers version included");

namespace DistrictsData {

struct Point;

struct Ring;
struct RingBuilder;

struct Polygon;
struct PolygonBuilder;

struct MultiPolygon;
struct MultiPolygonBuilder;

struct DistrictInfo;
struct DistrictInfoBuilder;

struct DistrictEntry;
struct DistrictEntryBuilder;

struct Districts;
struct DistrictsBuilder;

enum GeometryUnion : uint8_t {
    GeometryUnion_NONE = 0,
    GeometryUnion_Polygon = 1,
    GeometryUnion_MultiPolygon = 2,
    GeometryUnion_MIN = GeometryUnion_NONE,
    GeometryUnion_MAX = GeometryUnion_MultiPolygon
};

inline const GeometryUnion (&EnumValuesGeometryUnion())[3] {  // NOLINT
    static const GeometryUnion values[] = {
        GeometryUnion_NONE, GeometryUnion_Polygon, GeometryUnion_MultiPolygon};
    return values;
}

inline const char* const* EnumNamesGeometryUnion() {
    static const char* const names[4] = {"NONE", "Polygon", "MultiPolygon",
                                         nullptr};
    return names;
}

inline const char* EnumNameGeometryUnion(GeometryUnion e) {
    if (::flatbuffers::IsOutRange(e, GeometryUnion_NONE,
                                  GeometryUnion_MultiPolygon))
        return "";
    const size_t index = static_cast<size_t>(e);
    return EnumNamesGeometryUnion()[index];
}

template <typename T>
struct GeometryUnionTraits {
    static const GeometryUnion enum_value = GeometryUnion_NONE;
};

template <>
struct GeometryUnionTraits<DistrictsData::Polygon> {
    static const GeometryUnion enum_value = GeometryUnion_Polygon;
};

template <>
struct GeometryUnionTraits<DistrictsData::MultiPolygon> {
    static const GeometryUnion enum_value = GeometryUnion_MultiPolygon;
};

bool VerifyGeometryUnion(::flatbuffers::Verifier& verifier, const void* obj,
                         GeometryUnion type);
bool VerifyGeometryUnionVector(
    ::flatbuffers::Verifier& verifier,
    const ::flatbuffers::Vector<::flatbuffers::Offset<void>>* values,
    const ::flatbuffers::Vector<uint8_t>* types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Point FLATBUFFERS_FINAL_CLASS {
 private:
    double x_;
    double y_;

 public:
    Point() : x_(0), y_(0) {}
    Point(double _x, double _y)
        : x_(::flatbuffers::EndianScalar(_x)),
          y_(::flatbuffers::EndianScalar(_y)) {}
    double x() const { return ::flatbuffers::EndianScalar(x_); }
    double y() const { return ::flatbuffers::EndianScalar(y_); }
};
FLATBUFFERS_STRUCT_END(Point, 16);

struct Ring FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef RingBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_POINTS = 4
    };
    const ::flatbuffers::Vector<const DistrictsData::Point*>* points() const {
        return GetPointer<
            const ::flatbuffers::Vector<const DistrictsData::Point*>*>(
            VT_POINTS);
    }
    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) &&
               VerifyOffset(verifier, VT_POINTS) &&
               verifier.VerifyVector(points()) && verifier.EndTable();
    }
};

struct RingBuilder {
    typedef Ring Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_points(::flatbuffers::Offset<
                    ::flatbuffers::Vector<const DistrictsData::Point*>>
                        points) {
        fbb_.AddOffset(Ring::VT_POINTS, points);
    }
    explicit RingBuilder(::flatbuffers::FlatBufferBuilder& _fbb) : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<Ring> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<Ring>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<Ring> CreateRing(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const DistrictsData::Point*>>
        points = 0) {
    RingBuilder builder_(_fbb);
    builder_.add_points(points);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<Ring> CreateRingDirect(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    const std::vector<DistrictsData::Point>* points = nullptr) {
    auto points__ =
        points ? _fbb.CreateVectorOfStructs<DistrictsData::Point>(*points) : 0;
    return DistrictsData::CreateRing(_fbb, points__);
}

struct Polygon FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef PolygonBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_EXTERIOR = 4,
        VT_HOLES = 6
    };
    const DistrictsData::Ring* exterior() const {
        return GetPointer<const DistrictsData::Ring*>(VT_EXTERIOR);
    }
    const ::flatbuffers::Vector<::flatbuffers::Offset<DistrictsData::Ring>>*
    holes() const {
        return GetPointer<const ::flatbuffers::Vector<
            ::flatbuffers::Offset<DistrictsData::Ring>>*>(VT_HOLES);
    }
    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) &&
               VerifyOffset(verifier, VT_EXTERIOR) &&
               verifier.VerifyTable(exterior()) &&
               VerifyOffset(verifier, VT_HOLES) &&
               verifier.VerifyVector(holes()) &&
               verifier.VerifyVectorOfTables(holes()) && verifier.EndTable();
    }
};

struct PolygonBuilder {
    typedef Polygon Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_exterior(::flatbuffers::Offset<DistrictsData::Ring> exterior) {
        fbb_.AddOffset(Polygon::VT_EXTERIOR, exterior);
    }
    void add_holes(
        ::flatbuffers::Offset<
            ::flatbuffers::Vector<::flatbuffers::Offset<DistrictsData::Ring>>>
            holes) {
        fbb_.AddOffset(Polygon::VT_HOLES, holes);
    }
    explicit PolygonBuilder(::flatbuffers::FlatBufferBuilder& _fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<Polygon> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<Polygon>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<Polygon> CreatePolygon(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    ::flatbuffers::Offset<DistrictsData::Ring> exterior = 0,
    ::flatbuffers::Offset<
        ::flatbuffers::Vector<::flatbuffers::Offset<DistrictsData::Ring>>>
        holes = 0) {
    PolygonBuilder builder_(_fbb);
    builder_.add_holes(holes);
    builder_.add_exterior(exterior);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<Polygon> CreatePolygonDirect(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    ::flatbuffers::Offset<DistrictsData::Ring> exterior = 0,
    const std::vector<::flatbuffers::Offset<DistrictsData::Ring>>* holes =
        nullptr) {
    auto holes__ =
        holes ? _fbb.CreateVector<::flatbuffers::Offset<DistrictsData::Ring>>(
                    *holes)
              : 0;
    return DistrictsData::CreatePolygon(_fbb, exterior, holes__);
}

struct MultiPolygon FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef MultiPolygonBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_POLYS = 4
    };
    const ::flatbuffers::Vector<::flatbuffers::Offset<DistrictsData::Polygon>>*
    polys() const {
        return GetPointer<const ::flatbuffers::Vector<
            ::flatbuffers::Offset<DistrictsData::Polygon>>*>(VT_POLYS);
    }
    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) && VerifyOffset(verifier, VT_POLYS) &&
               verifier.VerifyVector(polys()) &&
               verifier.VerifyVectorOfTables(polys()) && verifier.EndTable();
    }
};

struct MultiPolygonBuilder {
    typedef MultiPolygon Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_polys(::flatbuffers::Offset<::flatbuffers::Vector<
                       ::flatbuffers::Offset<DistrictsData::Polygon>>>
                       polys) {
        fbb_.AddOffset(MultiPolygon::VT_POLYS, polys);
    }
    explicit MultiPolygonBuilder(::flatbuffers::FlatBufferBuilder& _fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<MultiPolygon> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<MultiPolygon>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<MultiPolygon> CreateMultiPolygon(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    ::flatbuffers::Offset<
        ::flatbuffers::Vector<::flatbuffers::Offset<DistrictsData::Polygon>>>
        polys = 0) {
    MultiPolygonBuilder builder_(_fbb);
    builder_.add_polys(polys);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<MultiPolygon> CreateMultiPolygonDirect(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    const std::vector<::flatbuffers::Offset<DistrictsData::Polygon>>* polys =
        nullptr) {
    auto polys__ =
        polys
            ? _fbb.CreateVector<::flatbuffers::Offset<DistrictsData::Polygon>>(
                  *polys)
            : 0;
    return DistrictsData::CreateMultiPolygon(_fbb, polys__);
}

struct DistrictInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef DistrictInfoBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_ID = 4,
        VT_NAME_EN = 6,
        VT_NAME = 8
    };
    uint32_t id() const { return GetField<uint32_t>(VT_ID, 0); }
    const ::flatbuffers::String* name_en() const {
        return GetPointer<const ::flatbuffers::String*>(VT_NAME_EN);
    }
    const ::flatbuffers::String* name() const {
        return GetPointer<const ::flatbuffers::String*>(VT_NAME);
    }
    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) &&
               VerifyField<uint32_t>(verifier, VT_ID, 4) &&
               VerifyOffset(verifier, VT_NAME_EN) &&
               verifier.VerifyString(name_en()) &&
               VerifyOffset(verifier, VT_NAME) &&
               verifier.VerifyString(name()) && verifier.EndTable();
    }
};

struct DistrictInfoBuilder {
    typedef DistrictInfo Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_id(uint32_t id) {
        fbb_.AddElement<uint32_t>(DistrictInfo::VT_ID, id, 0);
    }
    void add_name_en(::flatbuffers::Offset<::flatbuffers::String> name_en) {
        fbb_.AddOffset(DistrictInfo::VT_NAME_EN, name_en);
    }
    void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
        fbb_.AddOffset(DistrictInfo::VT_NAME, name);
    }
    explicit DistrictInfoBuilder(::flatbuffers::FlatBufferBuilder& _fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<DistrictInfo> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<DistrictInfo>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<DistrictInfo> CreateDistrictInfo(
    ::flatbuffers::FlatBufferBuilder& _fbb, uint32_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name_en = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0) {
    DistrictInfoBuilder builder_(_fbb);
    builder_.add_name(name);
    builder_.add_name_en(name_en);
    builder_.add_id(id);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<DistrictInfo> CreateDistrictInfoDirect(
    ::flatbuffers::FlatBufferBuilder& _fbb, uint32_t id = 0,
    const char* name_en = nullptr, const char* name = nullptr) {
    auto name_en__ = name_en ? _fbb.CreateString(name_en) : 0;
    auto name__ = name ? _fbb.CreateString(name) : 0;
    return DistrictsData::CreateDistrictInfo(_fbb, id, name_en__, name__);
}

struct DistrictEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef DistrictEntryBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_INFO = 4,
        VT_GEOM_TYPE = 6,
        VT_GEOM = 8
    };
    const DistrictsData::DistrictInfo* info() const {
        return GetPointer<const DistrictsData::DistrictInfo*>(VT_INFO);
    }
    DistrictsData::GeometryUnion geom_type() const {
        return static_cast<DistrictsData::GeometryUnion>(
            GetField<uint8_t>(VT_GEOM_TYPE, 0));
    }
    const void* geom() const { return GetPointer<const void*>(VT_GEOM); }
    template <typename T>
    const T* geom_as() const;
    const DistrictsData::Polygon* geom_as_Polygon() const {
        return geom_type() == DistrictsData::GeometryUnion_Polygon
                   ? static_cast<const DistrictsData::Polygon*>(geom())
                   : nullptr;
    }
    const DistrictsData::MultiPolygon* geom_as_MultiPolygon() const {
        return geom_type() == DistrictsData::GeometryUnion_MultiPolygon
                   ? static_cast<const DistrictsData::MultiPolygon*>(geom())
                   : nullptr;
    }
    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) && VerifyOffset(verifier, VT_INFO) &&
               verifier.VerifyTable(info()) &&
               VerifyField<uint8_t>(verifier, VT_GEOM_TYPE, 1) &&
               VerifyOffset(verifier, VT_GEOM) &&
               VerifyGeometryUnion(verifier, geom(), geom_type()) &&
               verifier.EndTable();
    }
};

template <>
inline const DistrictsData::Polygon*
DistrictEntry::geom_as<DistrictsData::Polygon>() const {
    return geom_as_Polygon();
}

template <>
inline const DistrictsData::MultiPolygon*
DistrictEntry::geom_as<DistrictsData::MultiPolygon>() const {
    return geom_as_MultiPolygon();
}

struct DistrictEntryBuilder {
    typedef DistrictEntry Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_info(::flatbuffers::Offset<DistrictsData::DistrictInfo> info) {
        fbb_.AddOffset(DistrictEntry::VT_INFO, info);
    }
    void add_geom_type(DistrictsData::GeometryUnion geom_type) {
        fbb_.AddElement<uint8_t>(DistrictEntry::VT_GEOM_TYPE,
                                 static_cast<uint8_t>(geom_type), 0);
    }
    void add_geom(::flatbuffers::Offset<void> geom) {
        fbb_.AddOffset(DistrictEntry::VT_GEOM, geom);
    }
    explicit DistrictEntryBuilder(::flatbuffers::FlatBufferBuilder& _fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<DistrictEntry> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<DistrictEntry>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<DistrictEntry> CreateDistrictEntry(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    ::flatbuffers::Offset<DistrictsData::DistrictInfo> info = 0,
    DistrictsData::GeometryUnion geom_type = DistrictsData::GeometryUnion_NONE,
    ::flatbuffers::Offset<void> geom = 0) {
    DistrictEntryBuilder builder_(_fbb);
    builder_.add_geom(geom);
    builder_.add_info(info);
    builder_.add_geom_type(geom_type);
    return builder_.Finish();
}

struct Districts FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef DistrictsBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_DATA = 4
    };
    const ::flatbuffers::Vector<
        ::flatbuffers::Offset<DistrictsData::DistrictEntry>>*
    data() const {
        return GetPointer<const ::flatbuffers::Vector<
            ::flatbuffers::Offset<DistrictsData::DistrictEntry>>*>(VT_DATA);
    }
    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) && VerifyOffset(verifier, VT_DATA) &&
               verifier.VerifyVector(data()) &&
               verifier.VerifyVectorOfTables(data()) && verifier.EndTable();
    }
};

struct DistrictsBuilder {
    typedef Districts Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_data(::flatbuffers::Offset<::flatbuffers::Vector<
                      ::flatbuffers::Offset<DistrictsData::DistrictEntry>>>
                      data) {
        fbb_.AddOffset(Districts::VT_DATA, data);
    }
    explicit DistrictsBuilder(::flatbuffers::FlatBufferBuilder& _fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<Districts> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<Districts>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<Districts> CreateDistricts(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<
        ::flatbuffers::Offset<DistrictsData::DistrictEntry>>>
        data = 0) {
    DistrictsBuilder builder_(_fbb);
    builder_.add_data(data);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<Districts> CreateDistrictsDirect(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    const std::vector<::flatbuffers::Offset<DistrictsData::DistrictEntry>>*
        data = nullptr) {
    auto data__ =
        data ? _fbb.CreateVector<
                   ::flatbuffers::Offset<DistrictsData::DistrictEntry>>(*data)
             : 0;
    return DistrictsData::CreateDistricts(_fbb, data__);
}

inline bool VerifyGeometryUnion(::flatbuffers::Verifier& verifier,
                                const void* obj, GeometryUnion type) {
    switch (type) {
        case GeometryUnion_NONE: {
            return true;
        }
        case GeometryUnion_Polygon: {
            auto ptr = reinterpret_cast<const DistrictsData::Polygon*>(obj);
            return verifier.VerifyTable(ptr);
        }
        case GeometryUnion_MultiPolygon: {
            auto ptr =
                reinterpret_cast<const DistrictsData::MultiPolygon*>(obj);
            return verifier.VerifyTable(ptr);
        }
        default:
            return true;
    }
}

inline bool VerifyGeometryUnionVector(
    ::flatbuffers::Verifier& verifier,
    const ::flatbuffers::Vector<::flatbuffers::Offset<void>>* values,
    const ::flatbuffers::Vector<uint8_t>* types) {
    if (!values || !types) return !values && !types;
    if (values->size() != types->size()) return false;
    for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
        if (!VerifyGeometryUnion(verifier, values->Get(i),
                                 types->GetEnum<GeometryUnion>(i))) {
            return false;
        }
    }
    return true;
}

inline const DistrictsData::Districts* GetDistricts(const void* buf) {
    return ::flatbuffers::GetRoot<DistrictsData::Districts>(buf);
}

inline const DistrictsData::Districts* GetSizePrefixedDistricts(
    const void* buf) {
    return ::flatbuffers::GetSizePrefixedRoot<DistrictsData::Districts>(buf);
}

inline bool VerifyDistrictsBuffer(::flatbuffers::Verifier& verifier) {
    return verifier.VerifyBuffer<DistrictsData::Districts>(nullptr);
}

inline bool VerifySizePrefixedDistrictsBuffer(
    ::flatbuffers::Verifier& verifier) {
    return verifier.VerifySizePrefixedBuffer<DistrictsData::Districts>(nullptr);
}

inline void FinishDistrictsBuffer(
    ::flatbuffers::FlatBufferBuilder& fbb,
    ::flatbuffers::Offset<DistrictsData::Districts> root) {
    fbb.Finish(root);
}

inline void FinishSizePrefixedDistrictsBuffer(
    ::flatbuffers::FlatBufferBuilder& fbb,
    ::flatbuffers::Offset<DistrictsData::Districts> root) {
    fbb.FinishSizePrefixed(root);
}

}  // namespace DistrictsData

#endif  // MODULES_FB_GENERATED_DISTRICTS_GENERATED_HPP_
