// Copyright 2025 itlab-vision
// automatically generated by the FlatBuffers compiler, do not modify

#ifndef MODULES_FB_GENERATED_DISTRICT_NEIGHBORS_GENERATED_HPP_
#define MODULES_FB_GENERATED_DISTRICT_NEIGHBORS_GENERATED_HPP_

#include <vector>
#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
                  FLATBUFFERS_VERSION_MINOR == 2 &&
                  FLATBUFFERS_VERSION_REVISION == 10,
              "Non-compatible flatbuffers version included");

namespace DistrictNeighborsData {

struct DistrictNeighborInfo;
struct DistrictNeighborInfoBuilder;

struct DistrictNeighbors;
struct DistrictNeighborsBuilder;

struct DistrictNeighborInfo FLATBUFFERS_FINAL_CLASS
    : private ::flatbuffers::Table {
    typedef DistrictNeighborInfoBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_DISTRICT_ID = 4,
        VT_NEIGHBORS = 6
    };
    uint32_t district_id() const {
        return GetField<uint32_t>(VT_DISTRICT_ID, 0);
    }
    const ::flatbuffers::Vector<uint32_t>* neighbors() const {
        return GetPointer<const ::flatbuffers::Vector<uint32_t>*>(VT_NEIGHBORS);
    }
    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) &&
               VerifyField<uint32_t>(verifier, VT_DISTRICT_ID, 4) &&
               VerifyOffset(verifier, VT_NEIGHBORS) &&
               verifier.VerifyVector(neighbors()) && verifier.EndTable();
    }
};

struct DistrictNeighborInfoBuilder {
    typedef DistrictNeighborInfo Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_district_id(uint32_t district_id) {
        fbb_.AddElement<uint32_t>(DistrictNeighborInfo::VT_DISTRICT_ID,
                                  district_id, 0);
    }
    void add_neighbors(
        ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> neighbors) {
        fbb_.AddOffset(DistrictNeighborInfo::VT_NEIGHBORS, neighbors);
    }
    explicit DistrictNeighborInfoBuilder(::flatbuffers::FlatBufferBuilder& _fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<DistrictNeighborInfo> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<DistrictNeighborInfo>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<DistrictNeighborInfo> CreateDistrictNeighborInfo(
    ::flatbuffers::FlatBufferBuilder& _fbb, uint32_t district_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> neighbors = 0) {
    DistrictNeighborInfoBuilder builder_(_fbb);
    builder_.add_neighbors(neighbors);
    builder_.add_district_id(district_id);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<DistrictNeighborInfo>
CreateDistrictNeighborInfoDirect(
    ::flatbuffers::FlatBufferBuilder& _fbb, uint32_t district_id = 0,
    const std::vector<uint32_t>* neighbors = nullptr) {
    auto neighbors__ = neighbors ? _fbb.CreateVector<uint32_t>(*neighbors) : 0;
    return DistrictNeighborsData::CreateDistrictNeighborInfo(_fbb, district_id,
                                                             neighbors__);
}

struct DistrictNeighbors FLATBUFFERS_FINAL_CLASS
    : private ::flatbuffers::Table {
    typedef DistrictNeighborsBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_DATA = 4
    };
    const ::flatbuffers::Vector<
        ::flatbuffers::Offset<DistrictNeighborsData::DistrictNeighborInfo>>*
    data() const {
        return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<
            DistrictNeighborsData::DistrictNeighborInfo>>*>(VT_DATA);
    }
    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) && VerifyOffset(verifier, VT_DATA) &&
               verifier.VerifyVector(data()) &&
               verifier.VerifyVectorOfTables(data()) && verifier.EndTable();
    }
};

struct DistrictNeighborsBuilder {
    typedef DistrictNeighbors Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_data(
        ::flatbuffers::Offset<::flatbuffers::Vector<
            ::flatbuffers::Offset<DistrictNeighborsData::DistrictNeighborInfo>>>
            data) {
        fbb_.AddOffset(DistrictNeighbors::VT_DATA, data);
    }
    explicit DistrictNeighborsBuilder(::flatbuffers::FlatBufferBuilder& _fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<DistrictNeighbors> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<DistrictNeighbors>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<DistrictNeighbors> CreateDistrictNeighbors(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<
        ::flatbuffers::Offset<DistrictNeighborsData::DistrictNeighborInfo>>>
        data = 0) {
    DistrictNeighborsBuilder builder_(_fbb);
    builder_.add_data(data);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<DistrictNeighbors> CreateDistrictNeighborsDirect(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    const std::vector<::flatbuffers::Offset<
        DistrictNeighborsData::DistrictNeighborInfo>>* data = nullptr) {
    auto data__ = data
                      ? _fbb.CreateVector<::flatbuffers::Offset<
                            DistrictNeighborsData::DistrictNeighborInfo>>(*data)
                      : 0;
    return DistrictNeighborsData::CreateDistrictNeighbors(_fbb, data__);
}

inline const DistrictNeighborsData::DistrictNeighbors* GetDistrictNeighbors(
    const void* buf) {
    return ::flatbuffers::GetRoot<DistrictNeighborsData::DistrictNeighbors>(
        buf);
}

inline const DistrictNeighborsData::DistrictNeighbors*
GetSizePrefixedDistrictNeighbors(const void* buf) {
    return ::flatbuffers::GetSizePrefixedRoot<
        DistrictNeighborsData::DistrictNeighbors>(buf);
}

inline bool VerifyDistrictNeighborsBuffer(::flatbuffers::Verifier& verifier) {
    return verifier.VerifyBuffer<DistrictNeighborsData::DistrictNeighbors>(
        nullptr);
}

inline bool VerifySizePrefixedDistrictNeighborsBuffer(
    ::flatbuffers::Verifier& verifier) {
    return verifier
        .VerifySizePrefixedBuffer<DistrictNeighborsData::DistrictNeighbors>(
            nullptr);
}

inline void FinishDistrictNeighborsBuffer(
    ::flatbuffers::FlatBufferBuilder& fbb,
    ::flatbuffers::Offset<DistrictNeighborsData::DistrictNeighbors> root) {
    fbb.Finish(root);
}

inline void FinishSizePrefixedDistrictNeighborsBuffer(
    ::flatbuffers::FlatBufferBuilder& fbb,
    ::flatbuffers::Offset<DistrictNeighborsData::DistrictNeighbors> root) {
    fbb.FinishSizePrefixed(root);
}

}  // namespace DistrictNeighborsData

#endif  // MODULES_FB_GENERATED_DISTRICT_NEIGHBORS_GENERATED_HPP_
