// Copyright 2025 itlab-vision
// automatically generated by the FlatBuffers compiler, do not modify

#ifndef MODULES_FB_GENERATED_SEGMENTS_GENERATED_HPP_
#define MODULES_FB_GENERATED_SEGMENTS_GENERATED_HPP_

#include <vector>
#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
                  FLATBUFFERS_VERSION_MINOR == 2 &&
                  FLATBUFFERS_VERSION_REVISION == 10,
              "Non-compatible flatbuffers version included");

namespace SegmentsData {

struct LatitudeRange;

struct LongitudeRange;

struct SegmentInfo;
struct SegmentInfoBuilder;

struct Segments;
struct SegmentsBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) LatitudeRange FLATBUFFERS_FINAL_CLASS {
 private:
    double min_;
    double max_;

 public:
    LatitudeRange() : min_(0), max_(0) {}
    LatitudeRange(double _min, double _max)
        : min_(::flatbuffers::EndianScalar(_min)),
          max_(::flatbuffers::EndianScalar(_max)) {}
    double min() const { return ::flatbuffers::EndianScalar(min_); }
    double max() const { return ::flatbuffers::EndianScalar(max_); }
};
FLATBUFFERS_STRUCT_END(LatitudeRange, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) LongitudeRange FLATBUFFERS_FINAL_CLASS {
 private:
    double min_;
    double max_;

 public:
    LongitudeRange() : min_(0), max_(0) {}
    LongitudeRange(double _min, double _max)
        : min_(::flatbuffers::EndianScalar(_min)),
          max_(::flatbuffers::EndianScalar(_max)) {}
    double min() const { return ::flatbuffers::EndianScalar(min_); }
    double max() const { return ::flatbuffers::EndianScalar(max_); }
};
FLATBUFFERS_STRUCT_END(LongitudeRange, 16);

struct SegmentInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef SegmentInfoBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_SEGMENT_ID = 4,
        VT_LAT_RANGE = 6,
        VT_LON_RANGE = 8,
        VT_NEIGHBORS = 10,
        VT_POINTS = 12
    };
    uint32_t segment_id() const { return GetField<uint32_t>(VT_SEGMENT_ID, 0); }
    const SegmentsData::LatitudeRange* lat_range() const {
        return GetStruct<const SegmentsData::LatitudeRange*>(VT_LAT_RANGE);
    }
    const SegmentsData::LongitudeRange* lon_range() const {
        return GetStruct<const SegmentsData::LongitudeRange*>(VT_LON_RANGE);
    }
    const ::flatbuffers::Vector<uint32_t>* neighbors() const {
        return GetPointer<const ::flatbuffers::Vector<uint32_t>*>(VT_NEIGHBORS);
    }
    const ::flatbuffers::Vector<uint32_t>* points() const {
        return GetPointer<const ::flatbuffers::Vector<uint32_t>*>(VT_POINTS);
    }
    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) &&
               VerifyField<uint32_t>(verifier, VT_SEGMENT_ID, 4) &&
               VerifyField<SegmentsData::LatitudeRange>(verifier, VT_LAT_RANGE,
                                                        8) &&
               VerifyField<SegmentsData::LongitudeRange>(verifier, VT_LON_RANGE,
                                                         8) &&
               VerifyOffset(verifier, VT_NEIGHBORS) &&
               verifier.VerifyVector(neighbors()) &&
               VerifyOffset(verifier, VT_POINTS) &&
               verifier.VerifyVector(points()) && verifier.EndTable();
    }
};

struct SegmentInfoBuilder {
    typedef SegmentInfo Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_segment_id(uint32_t segment_id) {
        fbb_.AddElement<uint32_t>(SegmentInfo::VT_SEGMENT_ID, segment_id, 0);
    }
    void add_lat_range(const SegmentsData::LatitudeRange* lat_range) {
        fbb_.AddStruct(SegmentInfo::VT_LAT_RANGE, lat_range);
    }
    void add_lon_range(const SegmentsData::LongitudeRange* lon_range) {
        fbb_.AddStruct(SegmentInfo::VT_LON_RANGE, lon_range);
    }
    void add_neighbors(
        ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> neighbors) {
        fbb_.AddOffset(SegmentInfo::VT_NEIGHBORS, neighbors);
    }
    void add_points(
        ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> points) {
        fbb_.AddOffset(SegmentInfo::VT_POINTS, points);
    }
    explicit SegmentInfoBuilder(::flatbuffers::FlatBufferBuilder& _fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<SegmentInfo> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<SegmentInfo>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<SegmentInfo> CreateSegmentInfo(
    ::flatbuffers::FlatBufferBuilder& _fbb, uint32_t segment_id = 0,
    const SegmentsData::LatitudeRange* lat_range = nullptr,
    const SegmentsData::LongitudeRange* lon_range = nullptr,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> neighbors = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> points = 0) {
    SegmentInfoBuilder builder_(_fbb);
    builder_.add_points(points);
    builder_.add_neighbors(neighbors);
    builder_.add_lon_range(lon_range);
    builder_.add_lat_range(lat_range);
    builder_.add_segment_id(segment_id);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<SegmentInfo> CreateSegmentInfoDirect(
    ::flatbuffers::FlatBufferBuilder& _fbb, uint32_t segment_id = 0,
    const SegmentsData::LatitudeRange* lat_range = nullptr,
    const SegmentsData::LongitudeRange* lon_range = nullptr,
    const std::vector<uint32_t>* neighbors = nullptr,
    const std::vector<uint32_t>* points = nullptr) {
    auto neighbors__ = neighbors ? _fbb.CreateVector<uint32_t>(*neighbors) : 0;
    auto points__ = points ? _fbb.CreateVector<uint32_t>(*points) : 0;
    return SegmentsData::CreateSegmentInfo(_fbb, segment_id, lat_range,
                                           lon_range, neighbors__, points__);
}

struct Segments FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef SegmentsBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_DATA = 4
    };
    const ::flatbuffers::Vector<
        ::flatbuffers::Offset<SegmentsData::SegmentInfo>>*
    data() const {
        return GetPointer<const ::flatbuffers::Vector<
            ::flatbuffers::Offset<SegmentsData::SegmentInfo>>*>(VT_DATA);
    }
    bool Verify(::flatbuffers::Verifier& verifier) const {
        return VerifyTableStart(verifier) && VerifyOffset(verifier, VT_DATA) &&
               verifier.VerifyVector(data()) &&
               verifier.VerifyVectorOfTables(data()) && verifier.EndTable();
    }
};

struct SegmentsBuilder {
    typedef Segments Table;
    ::flatbuffers::FlatBufferBuilder& fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_data(::flatbuffers::Offset<::flatbuffers::Vector<
                      ::flatbuffers::Offset<SegmentsData::SegmentInfo>>>
                      data) {
        fbb_.AddOffset(Segments::VT_DATA, data);
    }
    explicit SegmentsBuilder(::flatbuffers::FlatBufferBuilder& _fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<Segments> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<Segments>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<Segments> CreateSegments(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    ::flatbuffers::Offset<
        ::flatbuffers::Vector<::flatbuffers::Offset<SegmentsData::SegmentInfo>>>
        data = 0) {
    SegmentsBuilder builder_(_fbb);
    builder_.add_data(data);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<Segments> CreateSegmentsDirect(
    ::flatbuffers::FlatBufferBuilder& _fbb,
    const std::vector<::flatbuffers::Offset<SegmentsData::SegmentInfo>>* data =
        nullptr) {
    auto data__ =
        data ? _fbb.CreateVector<
                   ::flatbuffers::Offset<SegmentsData::SegmentInfo>>(*data)
             : 0;
    return SegmentsData::CreateSegments(_fbb, data__);
}

inline const SegmentsData::Segments* GetSegments(const void* buf) {
    return ::flatbuffers::GetRoot<SegmentsData::Segments>(buf);
}

inline const SegmentsData::Segments* GetSizePrefixedSegments(const void* buf) {
    return ::flatbuffers::GetSizePrefixedRoot<SegmentsData::Segments>(buf);
}

inline bool VerifySegmentsBuffer(::flatbuffers::Verifier& verifier) {
    return verifier.VerifyBuffer<SegmentsData::Segments>(nullptr);
}

inline bool VerifySizePrefixedSegmentsBuffer(
    ::flatbuffers::Verifier& verifier) {
    return verifier.VerifySizePrefixedBuffer<SegmentsData::Segments>(nullptr);
}

inline void FinishSegmentsBuffer(
    ::flatbuffers::FlatBufferBuilder& fbb,
    ::flatbuffers::Offset<SegmentsData::Segments> root) {
    fbb.Finish(root);
}

inline void FinishSizePrefixedSegmentsBuffer(
    ::flatbuffers::FlatBufferBuilder& fbb,
    ::flatbuffers::Offset<SegmentsData::Segments> root) {
    fbb.FinishSizePrefixed(root);
}

}  // namespace SegmentsData

#endif  // MODULES_FB_GENERATED_SEGMENTS_GENERATED_HPP_
