// Copyright 2025 itlab-vision
// automatically generated by the FlatBuffers compiler, do not modify

#ifndef INCLUDE_DISTRICT_NEIGHBORS_GENERATED_HPP_
#define INCLUDE_DISTRICT_NEIGHBORS_GENERATED_HPP_

#include <vector>

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
                  FLATBUFFERS_VERSION_MINOR == 2 &&
                  FLATBUFFERS_VERSION_REVISION == 10,
              "Non-compatible flatbuffers version included");

namespace DistrictNeighborsData {

struct District;
struct DistrictBuilder;

struct DistrictNeighbors;
struct DistrictNeighborsBuilder;

struct District FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef DistrictBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_ID = 4,
        VT_NEIGHBORS = 6
    };
    uint32_t id() const { return GetField<uint32_t>(VT_ID, 0); }
    bool KeyCompareLessThan(const District *const o) const {
        return id() < o->id();
    }
    int KeyCompareWithValue(uint32_t _id) const {
        return static_cast<int>(id() > _id) - static_cast<int>(id() < _id);
    }
    const ::flatbuffers::Vector<uint32_t> *neighbors() const {
        return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(
            VT_NEIGHBORS);
    }
    bool Verify(::flatbuffers::Verifier &verifier) const {
        return VerifyTableStart(verifier) &&
               VerifyField<uint32_t>(verifier, VT_ID, 4) &&
               VerifyOffset(verifier, VT_NEIGHBORS) &&
               verifier.VerifyVector(neighbors()) && verifier.EndTable();
    }
};

struct DistrictBuilder {
    typedef District Table;
    ::flatbuffers::FlatBufferBuilder &fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_id(uint32_t id) {
        fbb_.AddElement<uint32_t>(District::VT_ID, id, 0);
    }
    void add_neighbors(
        ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> neighbors) {
        fbb_.AddOffset(District::VT_NEIGHBORS, neighbors);
    }
    explicit DistrictBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<District> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<District>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<District> CreateDistrict(
    ::flatbuffers::FlatBufferBuilder &_fbb, uint32_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> neighbors = 0) {
    DistrictBuilder builder_(_fbb);
    builder_.add_neighbors(neighbors);
    builder_.add_id(id);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<District> CreateDistrictDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb, uint32_t id = 0,
    const std::vector<uint32_t> *neighbors = nullptr) {
    auto neighbors__ = neighbors ? _fbb.CreateVector<uint32_t>(*neighbors) : 0;
    return DistrictNeighborsData::CreateDistrict(_fbb, id, neighbors__);
}

struct DistrictNeighbors FLATBUFFERS_FINAL_CLASS
    : private ::flatbuffers ::Table {
    typedef DistrictNeighborsBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_DATA = 4
    };
    const ::flatbuffers::Vector<
        ::flatbuffers::Offset<DistrictNeighborsData::District>> *
    data() const {
        return GetPointer<const ::flatbuffers::Vector<
            ::flatbuffers::Offset<DistrictNeighborsData::District>> *>(VT_DATA);
    }
    bool Verify(::flatbuffers::Verifier &verifier) const {
        return VerifyTableStart(verifier) && VerifyOffset(verifier, VT_DATA) &&
               verifier.VerifyVector(data()) &&
               verifier.VerifyVectorOfTables(data()) && verifier.EndTable();
    }
};

struct DistrictNeighborsBuilder {
    typedef DistrictNeighbors Table;
    ::flatbuffers::FlatBufferBuilder &fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_data(::flatbuffers::Offset<::flatbuffers::Vector<
                      ::flatbuffers::Offset<DistrictNeighborsData::District>>>
                      data) {
        fbb_.AddOffset(DistrictNeighbors::VT_DATA, data);
    }
    explicit DistrictNeighborsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<DistrictNeighbors> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<DistrictNeighbors>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<DistrictNeighbors> CreateDistrictNeighbors(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<
        ::flatbuffers::Offset<DistrictNeighborsData::District>>>
        data = 0) {
    DistrictNeighborsBuilder builder_(_fbb);
    builder_.add_data(data);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<DistrictNeighbors> CreateDistrictNeighborsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    std::vector<::flatbuffers::Offset<DistrictNeighborsData::District>> *data =
        nullptr) {
    auto data__ =
        data ? _fbb.CreateVectorOfSortedTables<DistrictNeighborsData::District>(
                   data)
             : 0;
    return DistrictNeighborsData::CreateDistrictNeighbors(_fbb, data__);
}

inline const DistrictNeighborsData::DistrictNeighbors *GetDistrictNeighbors(
    const void *buf) {
    return ::flatbuffers::GetRoot<DistrictNeighborsData::DistrictNeighbors>(
        buf);
}

inline const DistrictNeighborsData::DistrictNeighbors *
GetSizePrefixedDistrictNeighbors(const void *buf) {
    return ::flatbuffers::GetSizePrefixedRoot<
        DistrictNeighborsData::DistrictNeighbors>(buf);
}

inline bool VerifyDistrictNeighborsBuffer(::flatbuffers::Verifier &verifier) {
    return verifier.VerifyBuffer<DistrictNeighborsData::DistrictNeighbors>(
        nullptr);
}

inline bool VerifySizePrefixedDistrictNeighborsBuffer(
    ::flatbuffers::Verifier &verifier) {
    return verifier
        .VerifySizePrefixedBuffer<DistrictNeighborsData::DistrictNeighbors>(
            nullptr);
}

inline void FinishDistrictNeighborsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<DistrictNeighborsData::DistrictNeighbors> root) {
    fbb.Finish(root);
}

inline void FinishSizePrefixedDistrictNeighborsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<DistrictNeighborsData::DistrictNeighbors> root) {
    fbb.FinishSizePrefixed(root);
}

}  // namespace DistrictNeighborsData

#endif  // INCLUDE_DISTRICT_NEIGHBORS_GENERATED_HPP_
