// Copyright 2025 itlab-vision
// automatically generated by the FlatBuffers compiler, do not modify

#ifndef INCLUDE_DISTRICTS_GENERATED_HPP_
#define INCLUDE_DISTRICTS_GENERATED_HPP_

#include <vector>

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
                  FLATBUFFERS_VERSION_MINOR == 2 &&
                  FLATBUFFERS_VERSION_REVISION == 10,
              "Non-compatible flatbuffers version included");

namespace DistrictsData {

struct Point;

struct Rect;

struct Ring;
struct RingBuilder;

struct Polygon;
struct PolygonBuilder;

struct MultiPolygon;
struct MultiPolygonBuilder;

struct Geometry;
struct GeometryBuilder;

struct DistrictInfo;
struct DistrictInfoBuilder;

struct DistrictEntry;
struct DistrictEntryBuilder;

struct Districts;
struct DistrictsBuilder;

enum GeometryType : int8_t {
    GeometryType_Unknown = 0,
    GeometryType_Point = 1,
    GeometryType_LineString = 2,
    GeometryType_Polygon = 3,
    GeometryType_MultiPoint = 4,
    GeometryType_MultiLineString = 5,
    GeometryType_MultiPolygon = 6,
    GeometryType_GeometryCollection = 7,
    GeometryType_MIN = GeometryType_Unknown,
    GeometryType_MAX = GeometryType_GeometryCollection
};

inline const GeometryType (&EnumValuesGeometryType())[8] {  // NOLINT
    static const GeometryType values[] = {
        GeometryType_Unknown,      GeometryType_Point,
        GeometryType_LineString,   GeometryType_Polygon,
        GeometryType_MultiPoint,   GeometryType_MultiLineString,
        GeometryType_MultiPolygon, GeometryType_GeometryCollection};
    return values;
}

inline const char *const *EnumNamesGeometryType() {
    static const char *const names[9] = {
        "Unknown",    "Point",           "LineString",   "Polygon",
        "MultiPoint", "MultiLineString", "MultiPolygon", "GeometryCollection",
        nullptr};
    return names;
}

inline const char *EnumNameGeometryType(GeometryType e) {
    if (::flatbuffers::IsOutRange(e, GeometryType_Unknown,
                                  GeometryType_GeometryCollection))
        return "";
    const size_t index = static_cast<size_t>(e);
    return EnumNamesGeometryType()[index];
}

enum GeometryUnion : uint8_t {
    GeometryUnion_NONE = 0,
    GeometryUnion_Point = 1,
    GeometryUnion_Ring = 2,
    GeometryUnion_Polygon = 3,
    GeometryUnion_MultiPolygon = 4,
    GeometryUnion_MIN = GeometryUnion_NONE,
    GeometryUnion_MAX = GeometryUnion_MultiPolygon
};

inline const GeometryUnion (&EnumValuesGeometryUnion())[5] {  // NOLINT
    static const GeometryUnion values[] = {
        GeometryUnion_NONE, GeometryUnion_Point, GeometryUnion_Ring,
        GeometryUnion_Polygon, GeometryUnion_MultiPolygon};
    return values;
}

inline const char *const *EnumNamesGeometryUnion() {
    static const char *const names[6] = {"NONE",    "Point",        "Ring",
                                         "Polygon", "MultiPolygon", nullptr};
    return names;
}

inline const char *EnumNameGeometryUnion(GeometryUnion e) {
    if (::flatbuffers::IsOutRange(e, GeometryUnion_NONE,
                                  GeometryUnion_MultiPolygon))
        return "";
    const size_t index = static_cast<size_t>(e);
    return EnumNamesGeometryUnion()[index];
}

template <typename T>
struct GeometryUnionTraits {
    static const GeometryUnion enum_value = GeometryUnion_NONE;
};

template <>
struct GeometryUnionTraits<DistrictsData::Point> {
    static const GeometryUnion enum_value = GeometryUnion_Point;
};

template <>
struct GeometryUnionTraits<DistrictsData::Ring> {
    static const GeometryUnion enum_value = GeometryUnion_Ring;
};

template <>
struct GeometryUnionTraits<DistrictsData::Polygon> {
    static const GeometryUnion enum_value = GeometryUnion_Polygon;
};

template <>
struct GeometryUnionTraits<DistrictsData::MultiPolygon> {
    static const GeometryUnion enum_value = GeometryUnion_MultiPolygon;
};

bool VerifyGeometryUnion(::flatbuffers::Verifier &verifier, const void *obj,
                         GeometryUnion type);
bool VerifyGeometryUnionVector(
    ::flatbuffers::Verifier &verifier,
    const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values,
    const ::flatbuffers::Vector<uint8_t> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Point FLATBUFFERS_FINAL_CLASS {
 private:
    double x_;
    double y_;

 public:
    Point() : x_(0), y_(0) {}
    Point(double _x, double _y)
        : x_(::flatbuffers::EndianScalar(_x)),
          y_(::flatbuffers::EndianScalar(_y)) {}
    double x() const { return ::flatbuffers::EndianScalar(x_); }
    double y() const { return ::flatbuffers::EndianScalar(y_); }
};
FLATBUFFERS_STRUCT_END(Point, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Rect FLATBUFFERS_FINAL_CLASS {
 private:
    DistrictsData::Point min_;
    DistrictsData::Point max_;

 public:
    Rect() : min_(), max_() {}
    Rect(const DistrictsData::Point &_min, const DistrictsData::Point &_max)
        : min_(_min), max_(_max) {}
    const DistrictsData::Point &min() const { return min_; }
    const DistrictsData::Point &max() const { return max_; }
};
FLATBUFFERS_STRUCT_END(Rect, 32);

struct Ring FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef RingBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_POINTS = 4,
        VT_CLOSED = 6,
        VT_NPOINTS = 8,
        VT_AREA = 10,
        VT_BBOX = 12,
        VT_EXTRA_COORDS = 14,
        VT_NCOORDS_PER_VERTEX = 16
    };
    const ::flatbuffers::Vector<const DistrictsData::Point *> *points() const {
        return GetPointer<
            const ::flatbuffers::Vector<const DistrictsData::Point *> *>(
            VT_POINTS);
    }
    bool closed() const { return GetField<uint8_t>(VT_CLOSED, 1) != 0; }
    int32_t npoints() const { return GetField<int32_t>(VT_NPOINTS, 0); }
    double area() const { return GetField<double>(VT_AREA, 0.0); }
    const DistrictsData::Rect *bbox() const {
        return GetStruct<const DistrictsData::Rect *>(VT_BBOX);
    }
    const ::flatbuffers::Vector<double> *extra_coords() const {
        return GetPointer<const ::flatbuffers::Vector<double> *>(
            VT_EXTRA_COORDS);
    }
    int32_t ncoords_per_vertex() const {
        return GetField<int32_t>(VT_NCOORDS_PER_VERTEX, 0);
    }
    bool Verify(::flatbuffers::Verifier &verifier) const {
        return VerifyTableStart(verifier) &&
               VerifyOffsetRequired(verifier, VT_POINTS) &&
               verifier.VerifyVector(points()) &&
               VerifyField<uint8_t>(verifier, VT_CLOSED, 1) &&
               VerifyField<int32_t>(verifier, VT_NPOINTS, 4) &&
               VerifyField<double>(verifier, VT_AREA, 8) &&
               VerifyFieldRequired<DistrictsData::Rect>(verifier, VT_BBOX, 8) &&
               VerifyOffset(verifier, VT_EXTRA_COORDS) &&
               verifier.VerifyVector(extra_coords()) &&
               VerifyField<int32_t>(verifier, VT_NCOORDS_PER_VERTEX, 4) &&
               verifier.EndTable();
    }
};

struct RingBuilder {
    typedef Ring Table;
    ::flatbuffers::FlatBufferBuilder &fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_points(::flatbuffers::Offset<
                    ::flatbuffers::Vector<const DistrictsData::Point *>>
                        points) {
        fbb_.AddOffset(Ring::VT_POINTS, points);
    }
    void add_closed(bool closed) {
        fbb_.AddElement<uint8_t>(Ring::VT_CLOSED, static_cast<uint8_t>(closed),
                                 1);
    }
    void add_npoints(int32_t npoints) {
        fbb_.AddElement<int32_t>(Ring::VT_NPOINTS, npoints, 0);
    }
    void add_area(double area) {
        fbb_.AddElement<double>(Ring::VT_AREA, area, 0.0);
    }
    void add_bbox(const DistrictsData::Rect *bbox) {
        fbb_.AddStruct(Ring::VT_BBOX, bbox);
    }
    void add_extra_coords(
        ::flatbuffers::Offset<::flatbuffers::Vector<double>> extra_coords) {
        fbb_.AddOffset(Ring::VT_EXTRA_COORDS, extra_coords);
    }
    void add_ncoords_per_vertex(int32_t ncoords_per_vertex) {
        fbb_.AddElement<int32_t>(Ring::VT_NCOORDS_PER_VERTEX,
                                 ncoords_per_vertex, 0);
    }
    explicit RingBuilder(::flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<Ring> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<Ring>(end);
        fbb_.Required(o, Ring::VT_POINTS);
        fbb_.Required(o, Ring::VT_BBOX);
        return o;
    }
};

inline ::flatbuffers::Offset<Ring> CreateRing(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const DistrictsData::Point *>>
        points = 0,
    bool closed = true, int32_t npoints = 0, double area = 0.0,
    const DistrictsData::Rect *bbox = nullptr,
    ::flatbuffers::Offset<::flatbuffers::Vector<double>> extra_coords = 0,
    int32_t ncoords_per_vertex = 0) {
    RingBuilder builder_(_fbb);
    builder_.add_area(area);
    builder_.add_ncoords_per_vertex(ncoords_per_vertex);
    builder_.add_extra_coords(extra_coords);
    builder_.add_bbox(bbox);
    builder_.add_npoints(npoints);
    builder_.add_points(points);
    builder_.add_closed(closed);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<Ring> CreateRingDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<DistrictsData::Point> *points = nullptr,
    bool closed = true, int32_t npoints = 0, double area = 0.0,
    const DistrictsData::Rect *bbox = nullptr,
    const std::vector<double> *extra_coords = nullptr,
    int32_t ncoords_per_vertex = 0) {
    auto points__ =
        points ? _fbb.CreateVectorOfStructs<DistrictsData::Point>(*points) : 0;
    auto extra_coords__ =
        extra_coords ? _fbb.CreateVector<double>(*extra_coords) : 0;
    return DistrictsData::CreateRing(_fbb, points__, closed, npoints, area,
                                     bbox, extra_coords__, ncoords_per_vertex);
}

struct Polygon FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef PolygonBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_EXTERIOR = 4,
        VT_HOLES = 6,
        VT_NHOLES = 8,
        VT_BBOX = 10
    };
    const DistrictsData::Ring *exterior() const {
        return GetPointer<const DistrictsData::Ring *>(VT_EXTERIOR);
    }
    const ::flatbuffers::Vector<::flatbuffers::Offset<DistrictsData::Ring>> *
    holes() const {
        return GetPointer<const ::flatbuffers::Vector<
            ::flatbuffers::Offset<DistrictsData::Ring>> *>(VT_HOLES);
    }
    int32_t nholes() const { return GetField<int32_t>(VT_NHOLES, 0); }
    const DistrictsData::Rect *bbox() const {
        return GetStruct<const DistrictsData::Rect *>(VT_BBOX);
    }
    bool Verify(::flatbuffers::Verifier &verifier) const {
        return VerifyTableStart(verifier) &&
               VerifyOffsetRequired(verifier, VT_EXTERIOR) &&
               verifier.VerifyTable(exterior()) &&
               VerifyOffset(verifier, VT_HOLES) &&
               verifier.VerifyVector(holes()) &&
               verifier.VerifyVectorOfTables(holes()) &&
               VerifyField<int32_t>(verifier, VT_NHOLES, 4) &&
               VerifyFieldRequired<DistrictsData::Rect>(verifier, VT_BBOX, 8) &&
               verifier.EndTable();
    }
};

struct PolygonBuilder {
    typedef Polygon Table;
    ::flatbuffers::FlatBufferBuilder &fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_exterior(::flatbuffers::Offset<DistrictsData::Ring> exterior) {
        fbb_.AddOffset(Polygon::VT_EXTERIOR, exterior);
    }
    void add_holes(
        ::flatbuffers::Offset<
            ::flatbuffers::Vector<::flatbuffers::Offset<DistrictsData::Ring>>>
            holes) {
        fbb_.AddOffset(Polygon::VT_HOLES, holes);
    }
    void add_nholes(int32_t nholes) {
        fbb_.AddElement<int32_t>(Polygon::VT_NHOLES, nholes, 0);
    }
    void add_bbox(const DistrictsData::Rect *bbox) {
        fbb_.AddStruct(Polygon::VT_BBOX, bbox);
    }
    explicit PolygonBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<Polygon> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<Polygon>(end);
        fbb_.Required(o, Polygon::VT_EXTERIOR);
        fbb_.Required(o, Polygon::VT_BBOX);
        return o;
    }
};

inline ::flatbuffers::Offset<Polygon> CreatePolygon(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<DistrictsData::Ring> exterior = 0,
    ::flatbuffers::Offset<
        ::flatbuffers::Vector<::flatbuffers::Offset<DistrictsData::Ring>>>
        holes = 0,
    int32_t nholes = 0, const DistrictsData::Rect *bbox = nullptr) {
    PolygonBuilder builder_(_fbb);
    builder_.add_bbox(bbox);
    builder_.add_nholes(nholes);
    builder_.add_holes(holes);
    builder_.add_exterior(exterior);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<Polygon> CreatePolygonDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<DistrictsData::Ring> exterior = 0,
    const std::vector<::flatbuffers::Offset<DistrictsData::Ring>> *holes =
        nullptr,
    int32_t nholes = 0, const DistrictsData::Rect *bbox = nullptr) {
    auto holes__ =
        holes ? _fbb.CreateVector<::flatbuffers::Offset<DistrictsData::Ring>>(
                    *holes)
              : 0;
    return DistrictsData::CreatePolygon(_fbb, exterior, holes__, nholes, bbox);
}

struct MultiPolygon FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef MultiPolygonBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_POLYS = 4,
        VT_NPOLYS = 6,
        VT_BBOX = 8
    };
    const ::flatbuffers::Vector<::flatbuffers::Offset<DistrictsData::Polygon>> *
    polys() const {
        return GetPointer<const ::flatbuffers::Vector<
            ::flatbuffers::Offset<DistrictsData::Polygon>> *>(VT_POLYS);
    }
    int32_t npolys() const { return GetField<int32_t>(VT_NPOLYS, 0); }
    const DistrictsData::Rect *bbox() const {
        return GetStruct<const DistrictsData::Rect *>(VT_BBOX);
    }
    bool Verify(::flatbuffers::Verifier &verifier) const {
        return VerifyTableStart(verifier) &&
               VerifyOffsetRequired(verifier, VT_POLYS) &&
               verifier.VerifyVector(polys()) &&
               verifier.VerifyVectorOfTables(polys()) &&
               VerifyField<int32_t>(verifier, VT_NPOLYS, 4) &&
               VerifyFieldRequired<DistrictsData::Rect>(verifier, VT_BBOX, 8) &&
               verifier.EndTable();
    }
};

struct MultiPolygonBuilder {
    typedef MultiPolygon Table;
    ::flatbuffers::FlatBufferBuilder &fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_polys(::flatbuffers::Offset<::flatbuffers::Vector<
                       ::flatbuffers::Offset<DistrictsData::Polygon>>>
                       polys) {
        fbb_.AddOffset(MultiPolygon::VT_POLYS, polys);
    }
    void add_npolys(int32_t npolys) {
        fbb_.AddElement<int32_t>(MultiPolygon::VT_NPOLYS, npolys, 0);
    }
    void add_bbox(const DistrictsData::Rect *bbox) {
        fbb_.AddStruct(MultiPolygon::VT_BBOX, bbox);
    }
    explicit MultiPolygonBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<MultiPolygon> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<MultiPolygon>(end);
        fbb_.Required(o, MultiPolygon::VT_POLYS);
        fbb_.Required(o, MultiPolygon::VT_BBOX);
        return o;
    }
};

inline ::flatbuffers::Offset<MultiPolygon> CreateMultiPolygon(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<
        ::flatbuffers::Vector<::flatbuffers::Offset<DistrictsData::Polygon>>>
        polys = 0,
    int32_t npolys = 0, const DistrictsData::Rect *bbox = nullptr) {
    MultiPolygonBuilder builder_(_fbb);
    builder_.add_bbox(bbox);
    builder_.add_npolys(npolys);
    builder_.add_polys(polys);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<MultiPolygon> CreateMultiPolygonDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<DistrictsData::Polygon>> *polys =
        nullptr,
    int32_t npolys = 0, const DistrictsData::Rect *bbox = nullptr) {
    auto polys__ =
        polys
            ? _fbb.CreateVector<::flatbuffers::Offset<DistrictsData::Polygon>>(
                  *polys)
            : 0;
    return DistrictsData::CreateMultiPolygon(_fbb, polys__, npolys, bbox);
}

struct Geometry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef GeometryBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_GTYPE = 4,
        VT_GEOM_TYPE = 6,
        VT_GEOM = 8
    };
    DistrictsData::GeometryType gtype() const {
        return static_cast<DistrictsData::GeometryType>(
            GetField<int8_t>(VT_GTYPE, 0));
    }
    DistrictsData::GeometryUnion geom_type() const {
        return static_cast<DistrictsData::GeometryUnion>(
            GetField<uint8_t>(VT_GEOM_TYPE, 0));
    }
    const void *geom() const { return GetPointer<const void *>(VT_GEOM); }
    template <typename T>
    const T *geom_as() const;
    const DistrictsData::Point *geom_as_Point() const {
        return geom_type() == DistrictsData::GeometryUnion_Point
                   ? static_cast<const DistrictsData::Point *>(geom())
                   : nullptr;
    }
    const DistrictsData::Ring *geom_as_Ring() const {
        return geom_type() == DistrictsData::GeometryUnion_Ring
                   ? static_cast<const DistrictsData::Ring *>(geom())
                   : nullptr;
    }
    const DistrictsData::Polygon *geom_as_Polygon() const {
        return geom_type() == DistrictsData::GeometryUnion_Polygon
                   ? static_cast<const DistrictsData::Polygon *>(geom())
                   : nullptr;
    }
    const DistrictsData::MultiPolygon *geom_as_MultiPolygon() const {
        return geom_type() == DistrictsData::GeometryUnion_MultiPolygon
                   ? static_cast<const DistrictsData::MultiPolygon *>(geom())
                   : nullptr;
    }
    bool Verify(::flatbuffers::Verifier &verifier) const {
        return VerifyTableStart(verifier) &&
               VerifyField<int8_t>(verifier, VT_GTYPE, 1) &&
               VerifyField<uint8_t>(verifier, VT_GEOM_TYPE, 1) &&
               VerifyOffsetRequired(verifier, VT_GEOM) &&
               VerifyGeometryUnion(verifier, geom(), geom_type()) &&
               verifier.EndTable();
    }
};

template <>
inline const DistrictsData::Point *Geometry::geom_as<DistrictsData::Point>()
const {
    return geom_as_Point();
}

template <>
inline const DistrictsData::Ring *Geometry::geom_as<DistrictsData::Ring>()
const {
    return geom_as_Ring();
}

template <>
inline const DistrictsData::Polygon *Geometry::geom_as<DistrictsData::Polygon>()
const {
    return geom_as_Polygon();
}

template <>
inline const DistrictsData::MultiPolygon *
Geometry::geom_as<DistrictsData::MultiPolygon>() const {
    return geom_as_MultiPolygon();
}

struct GeometryBuilder {
    typedef Geometry Table;
    ::flatbuffers::FlatBufferBuilder &fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_gtype(DistrictsData::GeometryType gtype) {
        fbb_.AddElement<int8_t>(Geometry::VT_GTYPE, static_cast<int8_t>(gtype),
                                0);
    }
    void add_geom_type(DistrictsData::GeometryUnion geom_type) {
        fbb_.AddElement<uint8_t>(Geometry::VT_GEOM_TYPE,
                                 static_cast<uint8_t>(geom_type), 0);
    }
    void add_geom(::flatbuffers::Offset<void> geom) {
        fbb_.AddOffset(Geometry::VT_GEOM, geom);
    }
    explicit GeometryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<Geometry> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<Geometry>(end);
        fbb_.Required(o, Geometry::VT_GEOM);
        return o;
    }
};

inline ::flatbuffers::Offset<Geometry> CreateGeometry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    DistrictsData::GeometryType gtype = DistrictsData::GeometryType_Unknown,
    DistrictsData::GeometryUnion geom_type = DistrictsData::GeometryUnion_NONE,
    ::flatbuffers::Offset<void> geom = 0) {
    GeometryBuilder builder_(_fbb);
    builder_.add_geom(geom);
    builder_.add_geom_type(geom_type);
    builder_.add_gtype(gtype);
    return builder_.Finish();
}

struct DistrictInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef DistrictInfoBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_ID = 4,
        VT_NAME_EN = 6,
        VT_NAME = 8
    };
    uint32_t id() const { return GetField<uint32_t>(VT_ID, 0); }
    const ::flatbuffers::String *name_en() const {
        return GetPointer<const ::flatbuffers::String *>(VT_NAME_EN);
    }
    const ::flatbuffers::String *name() const {
        return GetPointer<const ::flatbuffers::String *>(VT_NAME);
    }
    bool Verify(::flatbuffers::Verifier &verifier) const {
        return VerifyTableStart(verifier) &&
               VerifyField<uint32_t>(verifier, VT_ID, 4) &&
               VerifyOffset(verifier, VT_NAME_EN) &&
               verifier.VerifyString(name_en()) &&
               VerifyOffset(verifier, VT_NAME) &&
               verifier.VerifyString(name()) && verifier.EndTable();
    }
};

struct DistrictInfoBuilder {
    typedef DistrictInfo Table;
    ::flatbuffers::FlatBufferBuilder &fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_id(uint32_t id) {
        fbb_.AddElement<uint32_t>(DistrictInfo::VT_ID, id, 0);
    }
    void add_name_en(::flatbuffers::Offset<::flatbuffers::String> name_en) {
        fbb_.AddOffset(DistrictInfo::VT_NAME_EN, name_en);
    }
    void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
        fbb_.AddOffset(DistrictInfo::VT_NAME, name);
    }
    explicit DistrictInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<DistrictInfo> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<DistrictInfo>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<DistrictInfo> CreateDistrictInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb, uint32_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name_en = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0) {
    DistrictInfoBuilder builder_(_fbb);
    builder_.add_name(name);
    builder_.add_name_en(name_en);
    builder_.add_id(id);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<DistrictInfo> CreateDistrictInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb, uint32_t id = 0,
    const char *name_en = nullptr, const char *name = nullptr) {
    auto name_en__ = name_en ? _fbb.CreateString(name_en) : 0;
    auto name__ = name ? _fbb.CreateString(name) : 0;
    return DistrictsData::CreateDistrictInfo(_fbb, id, name_en__, name__);
}

struct DistrictEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef DistrictEntryBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_INFO = 4,
        VT_GEOM = 6
    };
    const DistrictsData::DistrictInfo *info() const {
        return GetPointer<const DistrictsData::DistrictInfo *>(VT_INFO);
    }
    const DistrictsData::Geometry *geom() const {
        return GetPointer<const DistrictsData::Geometry *>(VT_GEOM);
    }
    bool Verify(::flatbuffers::Verifier &verifier) const {
        return VerifyTableStart(verifier) &&
               VerifyOffsetRequired(verifier, VT_INFO) &&
               verifier.VerifyTable(info()) &&
               VerifyOffsetRequired(verifier, VT_GEOM) &&
               verifier.VerifyTable(geom()) && verifier.EndTable();
    }
};

struct DistrictEntryBuilder {
    typedef DistrictEntry Table;
    ::flatbuffers::FlatBufferBuilder &fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_info(::flatbuffers::Offset<DistrictsData::DistrictInfo> info) {
        fbb_.AddOffset(DistrictEntry::VT_INFO, info);
    }
    void add_geom(::flatbuffers::Offset<DistrictsData::Geometry> geom) {
        fbb_.AddOffset(DistrictEntry::VT_GEOM, geom);
    }
    explicit DistrictEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<DistrictEntry> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<DistrictEntry>(end);
        fbb_.Required(o, DistrictEntry::VT_INFO);
        fbb_.Required(o, DistrictEntry::VT_GEOM);
        return o;
    }
};

inline ::flatbuffers::Offset<DistrictEntry> CreateDistrictEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<DistrictsData::DistrictInfo> info = 0,
    ::flatbuffers::Offset<DistrictsData::Geometry> geom = 0) {
    DistrictEntryBuilder builder_(_fbb);
    builder_.add_geom(geom);
    builder_.add_info(info);
    return builder_.Finish();
}

struct Districts FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef DistrictsBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_ENTRIES = 4,
        VT_VERSION = 6
    };
    const ::flatbuffers::Vector<
        ::flatbuffers::Offset<DistrictsData::DistrictEntry>> *
    entries() const {
        return GetPointer<const ::flatbuffers::Vector<
            ::flatbuffers::Offset<DistrictsData::DistrictEntry>> *>(VT_ENTRIES);
    }
    uint32_t version() const { return GetField<uint32_t>(VT_VERSION, 1); }
    bool Verify(::flatbuffers::Verifier &verifier) const {
        return VerifyTableStart(verifier) &&
               VerifyOffsetRequired(verifier, VT_ENTRIES) &&
               verifier.VerifyVector(entries()) &&
               verifier.VerifyVectorOfTables(entries()) &&
               VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
               verifier.EndTable();
    }
};

struct DistrictsBuilder {
    typedef Districts Table;
    ::flatbuffers::FlatBufferBuilder &fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_entries(::flatbuffers::Offset<::flatbuffers::Vector<
                         ::flatbuffers::Offset<DistrictsData::DistrictEntry>>>
                         entries) {
        fbb_.AddOffset(Districts::VT_ENTRIES, entries);
    }
    void add_version(uint32_t version) {
        fbb_.AddElement<uint32_t>(Districts::VT_VERSION, version, 1);
    }
    explicit DistrictsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<Districts> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<Districts>(end);
        fbb_.Required(o, Districts::VT_ENTRIES);
        return o;
    }
};

inline ::flatbuffers::Offset<Districts> CreateDistricts(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<
        ::flatbuffers::Offset<DistrictsData::DistrictEntry>>>
        entries = 0,
    uint32_t version = 1) {
    DistrictsBuilder builder_(_fbb);
    builder_.add_version(version);
    builder_.add_entries(entries);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<Districts> CreateDistrictsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<DistrictsData::DistrictEntry>>
        *entries = nullptr,
    uint32_t version = 1) {
    auto entries__ =
        entries
            ? _fbb.CreateVector<
                  ::flatbuffers::Offset<DistrictsData::DistrictEntry>>(*entries)
            : 0;
    return DistrictsData::CreateDistricts(_fbb, entries__, version);
}

inline bool VerifyGeometryUnion(::flatbuffers::Verifier &verifier,
                                const void *obj, GeometryUnion type) {
    switch (type) {
        case GeometryUnion_NONE: {
            return true;
        }
        case GeometryUnion_Point: {
            return verifier.VerifyField<DistrictsData::Point>(
                static_cast<const uint8_t *>(obj), 0, 8);
        }
        case GeometryUnion_Ring: {
            auto ptr = reinterpret_cast<const DistrictsData::Ring *>(obj);
            return verifier.VerifyTable(ptr);
        }
        case GeometryUnion_Polygon: {
            auto ptr = reinterpret_cast<const DistrictsData::Polygon *>(obj);
            return verifier.VerifyTable(ptr);
        }
        case GeometryUnion_MultiPolygon: {
            auto ptr =
                reinterpret_cast<const DistrictsData::MultiPolygon *>(obj);
            return verifier.VerifyTable(ptr);
        }
        default:
            return true;
    }
}

inline bool VerifyGeometryUnionVector(
    ::flatbuffers::Verifier &verifier,
    const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values,
    const ::flatbuffers::Vector<uint8_t> *types) {
    if (!values || !types) return !values && !types;
    if (values->size() != types->size()) return false;
    for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
        if (!VerifyGeometryUnion(verifier, values->Get(i),
                                 types->GetEnum<GeometryUnion>(i))) {
            return false;
        }
    }
    return true;
}

inline const DistrictsData::Districts *GetDistricts(const void *buf) {
    return ::flatbuffers::GetRoot<DistrictsData::Districts>(buf);
}

inline const DistrictsData::Districts *GetSizePrefixedDistricts(
    const void *buf) {
    return ::flatbuffers::GetSizePrefixedRoot<DistrictsData::Districts>(buf);
}

inline bool VerifyDistrictsBuffer(::flatbuffers::Verifier &verifier) {
    return verifier.VerifyBuffer<DistrictsData::Districts>(nullptr);
}

inline bool VerifySizePrefixedDistrictsBuffer(
    ::flatbuffers::Verifier &verifier) {
    return verifier.VerifySizePrefixedBuffer<DistrictsData::Districts>(nullptr);
}

inline void FinishDistrictsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<DistrictsData::Districts> root) {
    fbb.Finish(root);
}

inline void FinishSizePrefixedDistrictsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<DistrictsData::Districts> root) {
    fbb.FinishSizePrefixed(root);
}

}  // namespace DistrictsData

#endif  // INCLUDE_DISTRICTS_GENERATED_HPP_
