// Copyright 2025 itlab-vision
// automatically generated by the FlatBuffers compiler, do not modify

#ifndef INCLUDE_LOCATIONS_SEGMENTS_GENERATED_HPP_
#define INCLUDE_LOCATIONS_SEGMENTS_GENERATED_HPP_

#include <vector>
#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
                  FLATBUFFERS_VERSION_MINOR == 2 &&
                  FLATBUFFERS_VERSION_REVISION == 10,
              "Non-compatible flatbuffers version included");

namespace LocationsSegmentsData {

struct LatitudeRange;

struct LongitudeRange;

struct LocationsSegmentInfo;
struct LocationsSegmentInfoBuilder;

struct LocationsSegments;
struct LocationsSegmentsBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) LatitudeRange FLATBUFFERS_FINAL_CLASS {
 private:
    double min_;
    double max_;

 public:
    LatitudeRange() : min_(0), max_(0) {}
    LatitudeRange(double _min, double _max)
        : min_(::flatbuffers::EndianScalar(_min)),
          max_(::flatbuffers::EndianScalar(_max)) {}
    double min() const { return ::flatbuffers::EndianScalar(min_); }
    double max() const { return ::flatbuffers::EndianScalar(max_); }
};
FLATBUFFERS_STRUCT_END(LatitudeRange, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) LongitudeRange FLATBUFFERS_FINAL_CLASS {
 private:
    double min_;
    double max_;

 public:
    LongitudeRange() : min_(0), max_(0) {}
    LongitudeRange(double _min, double _max)
        : min_(::flatbuffers::EndianScalar(_min)),
          max_(::flatbuffers::EndianScalar(_max)) {}
    double min() const { return ::flatbuffers::EndianScalar(min_); }
    double max() const { return ::flatbuffers::EndianScalar(max_); }
};
FLATBUFFERS_STRUCT_END(LongitudeRange, 16);

struct LocationsSegmentInfo FLATBUFFERS_FINAL_CLASS
    : private ::flatbuffers::Table {
    typedef LocationsSegmentInfoBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_SEGMENT_ID = 4,
        VT_LAT_RANGE = 6,
        VT_LON_RANGE = 8,
        VT_NEIGHBORS = 10,
        VT_LOCATIONS = 12
    };
    uint32_t segment_id() const { return GetField<uint32_t>(VT_SEGMENT_ID, 0); }
    const LocationsSegmentsData::LatitudeRange *lat_range() const {
        return GetStruct<const LocationsSegmentsData::LatitudeRange *>(
            VT_LAT_RANGE);
    }
    const LocationsSegmentsData::LongitudeRange *lon_range() const {
        return GetStruct<const LocationsSegmentsData::LongitudeRange *>(
            VT_LON_RANGE);
    }
    const ::flatbuffers::Vector<uint32_t> *neighbors() const {
        return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(
            VT_NEIGHBORS);
    }
    const ::flatbuffers::Vector<uint32_t> *locations() const {
        return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(
            VT_LOCATIONS);
    }
    bool Verify(::flatbuffers::Verifier &verifier) const {
        return VerifyTableStart(verifier) &&
               VerifyField<uint32_t>(verifier, VT_SEGMENT_ID, 4) &&
               VerifyField<LocationsSegmentsData::LatitudeRange>(
                   verifier, VT_LAT_RANGE, 8) &&
               VerifyField<LocationsSegmentsData::LongitudeRange>(
                   verifier, VT_LON_RANGE, 8) &&
               VerifyOffset(verifier, VT_NEIGHBORS) &&
               verifier.VerifyVector(neighbors()) &&
               VerifyOffset(verifier, VT_LOCATIONS) &&
               verifier.VerifyVector(locations()) && verifier.EndTable();
    }
};

struct LocationsSegmentInfoBuilder {
    typedef LocationsSegmentInfo Table;
    ::flatbuffers::FlatBufferBuilder &fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_segment_id(uint32_t segment_id) {
        fbb_.AddElement<uint32_t>(LocationsSegmentInfo::VT_SEGMENT_ID,
                                  segment_id, 0);
    }
    void add_lat_range(const LocationsSegmentsData::LatitudeRange *lat_range) {
        fbb_.AddStruct(LocationsSegmentInfo::VT_LAT_RANGE, lat_range);
    }
    void add_lon_range(const LocationsSegmentsData::LongitudeRange *lon_range) {
        fbb_.AddStruct(LocationsSegmentInfo::VT_LON_RANGE, lon_range);
    }
    void add_neighbors(
        ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> neighbors) {
        fbb_.AddOffset(LocationsSegmentInfo::VT_NEIGHBORS, neighbors);
    }
    void add_locations(
        ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> locations) {
        fbb_.AddOffset(LocationsSegmentInfo::VT_LOCATIONS, locations);
    }
    explicit LocationsSegmentInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<LocationsSegmentInfo> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<LocationsSegmentInfo>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<LocationsSegmentInfo> CreateLocationsSegmentInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb, uint32_t segment_id = 0,
    const LocationsSegmentsData::LatitudeRange *lat_range = nullptr,
    const LocationsSegmentsData::LongitudeRange *lon_range = nullptr,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> neighbors = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> locations = 0) {
    LocationsSegmentInfoBuilder builder_(_fbb);
    builder_.add_locations(locations);
    builder_.add_neighbors(neighbors);
    builder_.add_lon_range(lon_range);
    builder_.add_lat_range(lat_range);
    builder_.add_segment_id(segment_id);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<LocationsSegmentInfo>
CreateLocationsSegmentInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb, uint32_t segment_id = 0,
    const LocationsSegmentsData::LatitudeRange *lat_range = nullptr,
    const LocationsSegmentsData::LongitudeRange *lon_range = nullptr,
    const std::vector<uint32_t> *neighbors = nullptr,
    const std::vector<uint32_t> *locations = nullptr) {
    auto neighbors__ = neighbors ? _fbb.CreateVector<uint32_t>(*neighbors) : 0;
    auto locations__ = locations ? _fbb.CreateVector<uint32_t>(*locations) : 0;
    return LocationsSegmentsData::CreateLocationsSegmentInfo(
        _fbb, segment_id, lat_range, lon_range, neighbors__, locations__);
}

struct LocationsSegments FLATBUFFERS_FINAL_CLASS
    : private ::flatbuffers::Table {
    typedef LocationsSegmentsBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_DATA = 4
    };
    const ::flatbuffers::Vector<
        ::flatbuffers::Offset<LocationsSegmentsData::LocationsSegmentInfo>> *
    data() const {
        return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<
            LocationsSegmentsData::LocationsSegmentInfo>> *>(VT_DATA);
    }
    bool Verify(::flatbuffers::Verifier &verifier) const {
        return VerifyTableStart(verifier) && VerifyOffset(verifier, VT_DATA) &&
               verifier.VerifyVector(data()) &&
               verifier.VerifyVectorOfTables(data()) && verifier.EndTable();
    }
};

struct LocationsSegmentsBuilder {
    typedef LocationsSegments Table;
    ::flatbuffers::FlatBufferBuilder &fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_data(
        ::flatbuffers::Offset<::flatbuffers::Vector<
            ::flatbuffers::Offset<LocationsSegmentsData::LocationsSegmentInfo>>>
            data) {
        fbb_.AddOffset(LocationsSegments::VT_DATA, data);
    }
    explicit LocationsSegmentsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<LocationsSegments> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<LocationsSegments>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<LocationsSegments> CreateLocationsSegments(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<
        ::flatbuffers::Offset<LocationsSegmentsData::LocationsSegmentInfo>>>
        data = 0) {
    LocationsSegmentsBuilder builder_(_fbb);
    builder_.add_data(data);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<LocationsSegments> CreateLocationsSegmentsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<
        LocationsSegmentsData::LocationsSegmentInfo>> *data = nullptr) {
    auto data__ = data
                      ? _fbb.CreateVector<::flatbuffers::Offset<
                            LocationsSegmentsData::LocationsSegmentInfo>>(*data)
                      : 0;
    return LocationsSegmentsData::CreateLocationsSegments(_fbb, data__);
}

inline const LocationsSegmentsData::LocationsSegments *GetLocationsSegments(
    const void *buf) {
    return ::flatbuffers::GetRoot<LocationsSegmentsData::LocationsSegments>(
        buf);
}

inline const LocationsSegmentsData::LocationsSegments *
GetSizePrefixedLocationsSegments(const void *buf) {
    return ::flatbuffers::GetSizePrefixedRoot<
        LocationsSegmentsData::LocationsSegments>(buf);
}

inline bool VerifyLocationsSegmentsBuffer(::flatbuffers::Verifier &verifier) {
    return verifier.VerifyBuffer<LocationsSegmentsData::LocationsSegments>(
        nullptr);
}

inline bool VerifySizePrefixedLocationsSegmentsBuffer(
    ::flatbuffers::Verifier &verifier) {
    return verifier
        .VerifySizePrefixedBuffer<LocationsSegmentsData::LocationsSegments>(
            nullptr);
}

inline void FinishLocationsSegmentsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<LocationsSegmentsData::LocationsSegments> root) {
    fbb.Finish(root);
}

inline void FinishSizePrefixedLocationsSegmentsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<LocationsSegmentsData::LocationsSegments> root) {
    fbb.FinishSizePrefixed(root);
}

}  // namespace LocationsSegmentsData

#endif  // INCLUDE_LOCATIONS_SEGMENTS_GENERATED_HPP_
