// Copyright 2025 itlab-vision
// automatically generated by the FlatBuffers compiler, do not modify

#ifndef INCLUDE_LOCATIONS_GENERATED_HPP_
#define INCLUDE_LOCATIONS_GENERATED_HPP_

#include <vector>

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
                  FLATBUFFERS_VERSION_MINOR == 2 &&
                  FLATBUFFERS_VERSION_REVISION == 10,
              "Non-compatible flatbuffers version included");

namespace LocationsData {

struct Coordinates;

struct LocationInfo;
struct LocationInfoBuilder;

struct Location;
struct LocationBuilder;

struct Locations;
struct LocationsBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Coordinates FLATBUFFERS_FINAL_CLASS {
 private:
    double latitude_;
    double longitude_;

 public:
    Coordinates() : latitude_(0), longitude_(0) {}
    Coordinates(double _latitude, double _longitude)
        : latitude_(::flatbuffers::EndianScalar(_latitude)),
          longitude_(::flatbuffers::EndianScalar(_longitude)) {}
    double latitude() const { return ::flatbuffers::EndianScalar(latitude_); }
    double longitude() const { return ::flatbuffers::EndianScalar(longitude_); }
};
FLATBUFFERS_STRUCT_END(Coordinates, 16);

struct LocationInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef LocationInfoBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_LOCATION_ID = 4,
        VT_COUNTRY = 6,
        VT_CITY = 8,
        VT_REGION_ID = 10,
        VT_DISTRICT_ID = 12,
        VT_ALT_NAMES = 14
    };
    uint32_t location_id() const {
        return GetField<uint32_t>(VT_LOCATION_ID, 0);
    }
    const ::flatbuffers::String *country() const {
        return GetPointer<const ::flatbuffers::String *>(VT_COUNTRY);
    }
    const ::flatbuffers::String *city() const {
        return GetPointer<const ::flatbuffers::String *>(VT_CITY);
    }
    int32_t region_id() const { return GetField<int32_t>(VT_REGION_ID, 0); }
    int32_t district_id() const { return GetField<int32_t>(VT_DISTRICT_ID, 0); }
    const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *
    alt_names() const {
        return GetPointer<const ::flatbuffers::Vector<
            ::flatbuffers::Offset<::flatbuffers::String>> *>(VT_ALT_NAMES);
    }
    bool Verify(::flatbuffers::Verifier &verifier) const {
        return VerifyTableStart(verifier) &&
               VerifyField<uint32_t>(verifier, VT_LOCATION_ID, 4) &&
               VerifyOffset(verifier, VT_COUNTRY) &&
               verifier.VerifyString(country()) &&
               VerifyOffset(verifier, VT_CITY) &&
               verifier.VerifyString(city()) &&
               VerifyField<int32_t>(verifier, VT_REGION_ID, 4) &&
               VerifyField<int32_t>(verifier, VT_DISTRICT_ID, 4) &&
               VerifyOffset(verifier, VT_ALT_NAMES) &&
               verifier.VerifyVector(alt_names()) &&
               verifier.VerifyVectorOfStrings(alt_names()) &&
               verifier.EndTable();
    }
};

struct LocationInfoBuilder {
    typedef LocationInfo Table;
    ::flatbuffers::FlatBufferBuilder &fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_location_id(uint32_t location_id) {
        fbb_.AddElement<uint32_t>(LocationInfo::VT_LOCATION_ID, location_id, 0);
    }
    void add_country(::flatbuffers::Offset<::flatbuffers::String> country) {
        fbb_.AddOffset(LocationInfo::VT_COUNTRY, country);
    }
    void add_city(::flatbuffers::Offset<::flatbuffers::String> city) {
        fbb_.AddOffset(LocationInfo::VT_CITY, city);
    }
    void add_region_id(int32_t region_id) {
        fbb_.AddElement<int32_t>(LocationInfo::VT_REGION_ID, region_id, 0);
    }
    void add_district_id(int32_t district_id) {
        fbb_.AddElement<int32_t>(LocationInfo::VT_DISTRICT_ID, district_id, 0);
    }
    void add_alt_names(
        ::flatbuffers::Offset<
            ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>>
            alt_names) {
        fbb_.AddOffset(LocationInfo::VT_ALT_NAMES, alt_names);
    }
    explicit LocationInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<LocationInfo> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<LocationInfo>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<LocationInfo> CreateLocationInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb, uint32_t location_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> country = 0,
    ::flatbuffers::Offset<::flatbuffers::String> city = 0,
    int32_t region_id = 0, int32_t district_id = 0,
    ::flatbuffers::Offset<
        ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>>
        alt_names = 0) {
    LocationInfoBuilder builder_(_fbb);
    builder_.add_alt_names(alt_names);
    builder_.add_district_id(district_id);
    builder_.add_region_id(region_id);
    builder_.add_city(city);
    builder_.add_country(country);
    builder_.add_location_id(location_id);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<LocationInfo> CreateLocationInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb, uint32_t location_id = 0,
    const char *country = nullptr, const char *city = nullptr,
    int32_t region_id = 0, int32_t district_id = 0,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *alt_names =
        nullptr) {
    auto country__ = country ? _fbb.CreateString(country) : 0;
    auto city__ = city ? _fbb.CreateString(city) : 0;
    auto alt_names__ =
        alt_names
            ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(
                  *alt_names)
            : 0;
    return LocationsData::CreateLocationInfo(_fbb, location_id, country__,
                                             city__, region_id, district_id,
                                             alt_names__);
}

struct Location FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef LocationBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_INFO = 4,
        VT_COORDS = 6
    };
    const LocationsData::LocationInfo *info() const {
        return GetPointer<const LocationsData::LocationInfo *>(VT_INFO);
    }
    const LocationsData::Coordinates *coords() const {
        return GetStruct<const LocationsData::Coordinates *>(VT_COORDS);
    }
    bool Verify(::flatbuffers::Verifier &verifier) const {
        return VerifyTableStart(verifier) && VerifyOffset(verifier, VT_INFO) &&
               verifier.VerifyTable(info()) &&
               VerifyField<LocationsData::Coordinates>(verifier, VT_COORDS,
                                                       8) &&
               verifier.EndTable();
    }
};

struct LocationBuilder {
    typedef Location Table;
    ::flatbuffers::FlatBufferBuilder &fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_info(::flatbuffers::Offset<LocationsData::LocationInfo> info) {
        fbb_.AddOffset(Location::VT_INFO, info);
    }
    void add_coords(const LocationsData::Coordinates *coords) {
        fbb_.AddStruct(Location::VT_COORDS, coords);
    }
    explicit LocationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<Location> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<Location>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<Location> CreateLocation(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<LocationsData::LocationInfo> info = 0,
    const LocationsData::Coordinates *coords = nullptr) {
    LocationBuilder builder_(_fbb);
    builder_.add_coords(coords);
    builder_.add_info(info);
    return builder_.Finish();
}

struct Locations FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
    typedef LocationsBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_DATA = 4
    };
    const ::flatbuffers::Vector<
        ::flatbuffers::Offset<LocationsData::Location>> *
    data() const {
        return GetPointer<const ::flatbuffers::Vector<
            ::flatbuffers::Offset<LocationsData::Location>> *>(VT_DATA);
    }
    bool Verify(::flatbuffers::Verifier &verifier) const {
        return VerifyTableStart(verifier) && VerifyOffset(verifier, VT_DATA) &&
               verifier.VerifyVector(data()) &&
               verifier.VerifyVectorOfTables(data()) && verifier.EndTable();
    }
};

struct LocationsBuilder {
    typedef Locations Table;
    ::flatbuffers::FlatBufferBuilder &fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_data(::flatbuffers::Offset<::flatbuffers::Vector<
                      ::flatbuffers::Offset<LocationsData::Location>>>
                      data) {
        fbb_.AddOffset(Locations::VT_DATA, data);
    }
    explicit LocationsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<Locations> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<Locations>(end);
        return o;
    }
};

inline ::flatbuffers::Offset<Locations> CreateLocations(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<
        ::flatbuffers::Vector<::flatbuffers::Offset<LocationsData::Location>>>
        data = 0) {
    LocationsBuilder builder_(_fbb);
    builder_.add_data(data);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<Locations> CreateLocationsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<LocationsData::Location>> *data =
        nullptr) {
    auto data__ =
        data
            ? _fbb.CreateVector<::flatbuffers::Offset<LocationsData::Location>>(
                  *data)
            : 0;
    return LocationsData::CreateLocations(_fbb, data__);
}

inline const LocationsData::Locations *GetLocations(const void *buf) {
    return ::flatbuffers::GetRoot<LocationsData::Locations>(buf);
}

inline const LocationsData::Locations *GetSizePrefixedLocations(
    const void *buf) {
    return ::flatbuffers::GetSizePrefixedRoot<LocationsData::Locations>(buf);
}

inline bool VerifyLocationsBuffer(::flatbuffers::Verifier &verifier) {
    return verifier.VerifyBuffer<LocationsData::Locations>(nullptr);
}

inline bool VerifySizePrefixedLocationsBuffer(
    ::flatbuffers::Verifier &verifier) {
    return verifier.VerifySizePrefixedBuffer<LocationsData::Locations>(nullptr);
}

inline void FinishLocationsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<LocationsData::Locations> root) {
    fbb.Finish(root);
}

inline void FinishSizePrefixedLocationsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<LocationsData::Locations> root) {
    fbb.FinishSizePrefixed(root);
}

}  // namespace LocationsData

#endif  // INCLUDE_LOCATIONS_GENERATED_HPP_
